export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAIL = 'GET_CART_FAIL'
export const GET_CART_RESET = 'GET_CART_RESET'

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'
export const ADD_TO_CART_RESET = 'ADD_TO_CART_RESET'

export const REDUCE_ITEM_FROM_CART_REQUEST = 'REDUCE_ITEM_FROM_CART_REQUEST'
export const REDUCE_ITEM_FROM_CART_SUCCESS = 'REDUCE_ITEM_FROM_CART_SUCCESS'
export const REDUCE_ITEM_FROM_CART_FAIL = 'REDUCE_ITEM_FROM_CART_FAIL'
export const REDUCE_ITEM_FROM_CART_RESET = 'REDUCE_ITEM_FROM_CART_RESET'

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST'
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL'
export const REMOVE_FROM_CART_RESET = 'ADD_TO_CART_RESET'

export const CART_RESET = 'CART_RESET'
