export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'
export const GET_PRODUCTS_RESET = 'GET_PRODUCTS_RESET'

export const GET_PRODUCT_DETAILS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST'
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL'
export const GET_PRODUCT_DETAILS_RESET = 'GET_PRODUCT_DETAILS_RESET'

export const POST_ADD_PRODUCT_REQUEST = 'POST_ADD_PRODUCT_REQUEST'
export const POST_ADD_PRODUCT_SUCCESS = 'POST_ADD_PRODUCT_SUCCESS'
export const POST_ADD_PRODUCT_FAIL = 'POST_ADD_PRODUCT_FAIL'
export const POST_ADD_PRODUCT_RESET = 'POST_ADD_PRODUCT_RESET'

export const PATCH_RESTOCK_PRODUCT_REQUEST = 'PATCH_RESTOCK_PRODUCT_REQUEST'
export const PATCH_RESTOCK_PRODUCT_SUCCESS = 'PATCH_RESTOCK_PRODUCT_SUCCESS'
export const PATCH_RESTOCK_PRODUCT_FAIL = 'PATCH_RESTOCK_PRODUCT_FAIL'
export const PATCH_RESTOCK_PRODUCT_RESET = 'PATCH_RESTOCK_PRODUCT_RESET'

export const PATCH_EDIT_PRODUCT_REQUEST = 'PATCH_EDIT_PRODUCT_REQUEST'
export const PATCH_EDIT_PRODUCT_SUCCESS = 'PATCH_EDIT_PRODUCT_SUCCESS'
export const PATCH_EDIT_PRODUCT_FAIL = 'PATCH_EDIT_PRODUCT_FAIL'
export const PATCH_EDIT_PRODUCT_RESET = 'PATCH_EDIT_PRODUCT_RESET'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET'
